import { Inter } from "@next/font/google";
import BottomListContent from "components/example/BottomListContent";
import Head from "next/head";
import Image from "next/image";
import styles from "styles/module/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Next.js + Tailwind CSS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-between min-h-screen p-24">
        <div className={`flex justify-between items-center text-sm max-w-[1100px] w-full z-[2] mono`}>
          <p className={`relative m-0 p-4 ${styles.block_code}`}>
            Get started by editing&nbsp;
            <code className="font-bold mono">pages/index.tsx</code>
          </p>
          <div>
            <a
              className="flex items-center justify-center gap-2"
              href="https://mltechsoft.com"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Image
                src="/images/webp/logo.webp"
                alt="Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={`${styles.center}`}>
          <Image className="relative" src="/next.svg" alt="Next.js Logo" width={180} height={37} priority />
          <div className={`${styles.thirteen} mr-8`}>
            <Image src="/thirteen.svg" alt="13" width={40} height={31} priority />
          </div>
          <div className={`self-center mr-8`}>
            <p className={`${inter.className} text-5xl`}>+</p>
          </div>
          <Image
            className="relative"
            src="/images/svg/tailwindcss-logo.svg"
            alt="Next.js Logo"
            width={250}
            height={40}
            priority
          />
        </div>

        <BottomListContent />
      </main>
    </>
  );
}
